/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pqexample;

/**
 *
 * @author TetianaPopova
 */
public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());
     MyPQ myPQList = new MyPQ();
    /**
     * Creates new form NewPQ
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PQkeyLabel = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        PQValueLabel = new javax.swing.JLabel();
        symptomTF = new javax.swing.JTextField();
        numberB = new javax.swing.JButton();
        listB = new javax.swing.JButton();
        addB = new javax.swing.JButton();
        editB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        priorityTF = new javax.swing.JTextField();
        removeB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PQkeyLabel.setText("Patient Name");

        nameTF.addActionListener(this::nameTFActionPerformed);

        PQValueLabel.setText("Symptom");

        symptomTF.addActionListener(this::symptomTFActionPerformed);

        numberB.setText("Number Patient in Q");
        numberB.addActionListener(this::numberBActionPerformed);

        listB.setText("List Patient");
        listB.addActionListener(this::listBActionPerformed);

        addB.setText("Add Patient");
        addB.addActionListener(this::addBActionPerformed);

        editB.setText("Edit");
        editB.addActionListener(this::editBActionPerformed);

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        jLabel1.setText("Welcome to Hospital!");

        jLabel2.setText("Priority");

        priorityTF.addActionListener(this::priorityTFActionPerformed);

        removeB.setText("Remove Patient");
        removeB.addActionListener(this::removeBActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numberB)
                                    .addGap(27, 27, 27)
                                    .addComponent(addB))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(listB)
                                    .addGap(73, 73, 73)
                                    .addComponent(editB)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PQkeyLabel)
                                .addComponent(PQValueLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(priorityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(symptomTF, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                    .addComponent(nameTF)))
                            .addContainerGap(38, Short.MAX_VALUE))))
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(removeB, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PQkeyLabel)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(symptomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PQValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(priorityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberB)
                    .addComponent(addB)
                    .addComponent(removeB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listB)
                    .addComponent(editB))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void symptomTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symptomTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symptomTFActionPerformed

    private void removeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBActionPerformed
        // TODO add your handling code here:      
        if(myPQList.size()==0){
           displayTA.append("Cannot remove, list is empty\n");  
        }else{
           Object tempPatient = myPQList.frontOfQueue();        
           myPQList.dequeue();
           displayTA.append(tempPatient.toString() +" was removed\n");
        }
    }//GEN-LAST:event_removeBActionPerformed
    
    private void priorityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorityTFActionPerformed

    private void listBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBActionPerformed
        // TODO add your handling code here:
        displayTA.append(myPQList.printQ()+"\n");
        
    }//GEN-LAST:event_listBActionPerformed

    private void editBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBActionPerformed
        // TODO add your handling code here:
        System.exit(0 );
    }//GEN-LAST:event_editBActionPerformed

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        // TODO add your handling code here:
        String patientName;
        String mainSymptom;
        int priority;
        patientName = nameTF.getText();
        mainSymptom = symptomTF.getText();
        priority =  Integer.parseInt(priorityTF.getText());
        
        Patient newPatient = new Patient();
        newPatient.setName(patientName);
        newPatient.setSymptom(mainSymptom);
        newPatient.setKey(priority);
        
       
        myPQList.enqueue(priority,newPatient);
        displayTA.append(patientName+" was added to the list\n");
        nameTF.setText("");
        symptomTF.setText("");
        priorityTF.setText("");
        
        
        
        
        
    }//GEN-LAST:event_addBActionPerformed

    private void numberBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBActionPerformed
        // TODO add your handling code here:
        displayTA.append(myPQList.size()+" person in the Q\n");
       
    }//GEN-LAST:event_numberBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PQValueLabel;
    private javax.swing.JLabel PQkeyLabel;
    private javax.swing.JButton addB;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton editB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listB;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton numberB;
    private javax.swing.JTextField priorityTF;
    private javax.swing.JButton removeB;
    private javax.swing.JTextField symptomTF;
    // End of variables declaration//GEN-END:variables
}
